<<<<<<< HEAD
# Generated by Django 2.2.12 on 2020-04-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('busyness', models.IntegerField()),
            ],
        ),
    ]
||||||| merged common ancestors
=======
# Generated by Django 2.2.9 on 2020-04-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('busyness', models.IntegerField()),
            ],
        ),
    ]
>>>>>>> master
