# Generated by Django 3.0.5 on 2020-04-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200425_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='hours',
            field=models.CharField(default='', max_length=100),
        ),
    ]
