# Generated by Django 2.2.12 on 2020-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200426_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='hours',
            new_name='frihours',
        ),
        migrations.AddField(
            model_name='store',
            name='monhours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sathours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sunhours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='thuhours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='tuehours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='wedhours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
