# Generated by Django 3.0.5 on 2020-05-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20200426_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='keywords',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
