# Generated by Django 2.2.12 on 2020-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_store_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author_name', models.CharField(max_length=100)),
                ('author_blurb', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=40000)),
            ],
        ),
    ]
