# Generated by Django 2.2.12 on 2020-05-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_blog_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_entry',
            name='article_sources',
            field=models.CharField(default='a source a source a source', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_entry',
            name='image_blurb',
            field=models.CharField(default='a blurb', max_length=500),
            preserve_default=False,
        ),
    ]
