# Generated by Django 2.2.12 on 2020-05-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20200515_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_entry',
            name='article_sources',
            field=models.CharField(max_length=10000),
        ),
    ]
