# Generated by Django 2.2.12 on 2020-06-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_store_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_entry',
            name='content',
            field=models.TextField(max_length=40000),
        ),
    ]
