# Generated by Django 2.2.12 on 2020-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20200603_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_blurb', models.TextField(max_length=10000)),
                ('ad_img_src', models.CharField(max_length=300)),
                ('ad_local_img', models.ImageField(upload_to='')),
                ('ad_link', models.CharField(max_length=1000)),
                ('ad_timestamp', models.DateTimeField()),
            ],
        ),
    ]
