# Generated by Django 2.2.12 on 2020-06-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_ad_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_placement',
            name='ad_local_img',
        ),
    ]
