# Generated by Django 2.2.12 on 2020-06-03 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_remove_ad_placement_ad_local_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_entry',
            name='article_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
