# Generated by Django 2.2.12 on 2020-06-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_blog_entry_article_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_placement',
            name='ad_city',
            field=models.CharField(default='vancouver, seattle', max_length=300),
            preserve_default=False,
        ),
    ]
