# Generated by Django 2.2.12 on 2020-06-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_auto_20200605_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_entry',
            old_name='article_timestamoed',
            new_name='article_timestamp',
        ),
    ]
