# Generated by Django 2.2.9 on 2020-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20200605_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_entry',
            name='img_src',
            field=models.CharField(default='http://drive.google.com/uc?id=1VgMaQckiTGqvmM9MzoBhhjb65SNsr_LF', max_length=200),
            preserve_default=False,
        ),
    ]
