# Generated by Django 2.2.12 on 2020-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_blog_entry_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_entry',
            name='article_sources',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_entry',
            name='author_blurb',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='blog_entry',
            name='author_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_entry',
            name='content',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='blog_entry',
            name='img_src',
            field=models.CharField(max_length=300),
        ),
    ]
